module.exports = ({
    name: "profil",
    code: `
    $color[$random[00;999999]]
    $onlyIf[$message[1]!=$mentioned[1];]
    $onlyIf[$message[1]==;]
    $author[$username[$authorID] profile ;$userAvatar[$replaceText[$replaceText[$checkCondition[$message[1]==$mentioned[1]];true;$mentioned[1]];false;$authorID]]]
    $thumbnail[$userAvatar[$authorID]]
    
    $description[
        <a:owner:741818171073232907> $replaceText[$replaceText[$checkCondition[$status[$replaceText[$replaceText[$checkCondition[$message[1]==$mentioned[1]];true;$mentioned[1]];false;$authorID]]==online];true;<:online:765645895685242891>];false;]$replaceText[$replaceText[$checkCondition[$status[$replaceText[$replaceText[$checkCondition[$message[1]==$mentioned[1]];true;$mentioned[1]];false;$authorID]]==dnd];true;<:dnd:751759197082877983>];false;]$replaceText[$replaceText[$checkCondition[$status[$replaceText[$replaceText[$checkCondition[$message[1]==$mentioned[1]];true;$mentioned[1]];false;$authorID]]==idle];true;<:idle:751759197095329822>];false;]$replaceText[$replaceText[$checkCondition[$status[$replaceText[$replaceText[$checkCondition[$message[1]==$mentioned[1]];true;$mentioned[1]];false;$authorID]]==offline];true;<:offline:765646063071264862>];false;]<@$authorID> $replaceText[$replaceText[$checkCondition[$getUserBadges[$authorID]==HOUSE_BALANCE];true;<:ballance:759899412704133130>];false;]$replaceText[$replaceText[$checkCondition[$getUserBadges[$authorID]==HOUSE_BRAVERY];true;<:bravery:759899316755759114>];false;]$replaceText[$replaceText[$checkCondition[$getUserBadges[$authorID]==HOUSE_BRILLIANCE];true;<:brillance:759900477369483265>];false;]
    
    **Rank:** $replaceText[$replaceText[$checkCondition[$getVar[prestige;;$replaceText[$replaceText[$checkCondition[$message[1]==$mentioned[1]];true;$mentioned[1]];false;$authorID]]==0];true;\`None\`\n{hyper:□□□□:https://www.youtube.com/watch?v=5_Xdi4T8mgI}];false;]$replaceText[$replaceText[$checkCondition[$getVar[prestige;$replaceText[$replaceText[$checkCondition[$message[1]==$mentioned[1]];true;$mentioned[1]];false;$authorID]]==1];true;<:prestiger1:749725312891224115>\n{hyper:■□□□:https://www.youtube.com/watch?v=5_Xdi4T8mgI}];false;]$replaceText[$replaceText[$checkCondition[$getVar[prestige;$replaceText[$replaceText[$checkCondition[$message[1]==$mentioned[1]];true;$mentioned[1]];false;$authorID]]==2];true;<:prestiger2:749725313050607626>\n{hyper:■■□□:https://www.youtube.com/watch?v=5_Xdi4T8mgI}];false;]$replaceText[$replaceText[$checkCondition[$getVar[prestige;$replaceText[$replaceText[$checkCondition[$message[1]==$mentioned[1]];true;$mentioned[1]];false;$authorID]]==3];true;<:prestiger3:749725312731971666>\n{hyper:■■■□:https://www.youtube.com/watch?v=5_Xdi4T8mgI}];false;]$replaceText[$replaceText[$checkCondition[$getVar[prestige;$replaceText[$replaceText[$checkCondition[$message[1]==$mentioned[1]];true;$mentioned[1]];false;$authorID]]>3];true;<:vip:766141422503067699>\n{hyper:■■■■:https://www.youtube.com/watch?v=5_Xdi4T8mgI}];false;]
    **Balance**:
    **$$getVar[money;$replaceText[$replaceText[$checkCondition[$message[1]==$mentioned[1]];true;$mentioned[1]];false;$authorID]]** Money 💰
    **$$getVar[Cash;$replaceText[$replaceText[$checkCondition[$message[1]==$mentioned[1]];true;$mentioned[1]];false;$authorID]]** Cash 💸     **| $$sum[$getVar[money;$replaceText[$replaceText[$checkCondition[$message[1]==$mentioned[1]];true;$mentioned[1]];false;$authorID]];$getVar[Cash;$replaceText[$replaceText[$checkCondition[$message[1]==$mentioned[1]];true;$mentioned[1]];false;$authorID]];$getVar[Bank;$replaceText[$replaceText[$checkCondition[$message[1]==$mentioned[1]];true;$mentioned[1]];false;$authorID]]]** Total 📊
    **$$getVar[Bank;$replaceText[$replaceText[$checkCondition[$message[1]==$mentioned[1]];true;$mentioned[1]];false;$authorID]]** en Bank :bank:

       🎖️**$getVar[réputation;$replaceText[$replaceText[$checkCondition[$message[1]==$mentioned[1]];true;$mentioned[1]];false;$authorID]]%** de réputation                       **Clan:** \`$getVar[clan;$replaceText[$replaceText[$checkCondition[$message[1]==$mentioned[1]];true;$mentioned[1]];false;$authorID]]\` $getVar[clanlogo;$replaceText[$replaceText[$checkCondition[$message[1]==$mentioned[1]];true;$mentioned[1]];false;$authorID]]
       $replaceText[$replaceText[$checkCondition[$getVar[Gooddeed;$replaceText[$replaceText[$checkCondition[$message[1]==$mentioned[1]];true;$mentioned[1]];false;]$replaceText[$replaceText[$checkCondition[$message[1]==];true;$authorID];false;]]>0];true;✨**$getVar[Gooddeed;$replaceText[$replaceText[$checkCondition[$message[1]==$mentioned[1]];true;$mentioned[1]];false;]$replaceText[$replaceText[$checkCondition[$message[1]==];true;$authorID];false;$authorID]]%** de bonnes actions];false; **<:no:765020908833341490> Mauvais personne**]              ** Point Bonus:** $replaceText[$replaceText[$checkCondition[$getVar[pointbonus]==0];true;\`Aucun\` <:nuk3economie:753772063604473888> ];false;$getVar[pointbonus] Point Bonus <:nuk3economie:753772063604473888>]     
       $replaceText[$replaceText[$checkCondition[$getVar[Police;$replaceText[$replaceText[$checkCondition[$message[1]==$mentioned[1]];true;$mentioned[1]];false;$authorID]]==0];true;👮**‍Aucun** Policier];false;**👮‍$getVar[Police;$replaceText[$replaceText[$checkCondition[$message[1]==$mentioned[1]];true;$mentioned[1]];false;$authorID]]** Policier(s) te surveille]
       👥 $replaceText[$replaceText[$checkCondition[$getVar[Amis;$replaceText[$replaceText[$checkCondition[$message[1]==$mentioned[1]];true;$mentioned[1]];false;$authorID]]==0];true;**Aucun**];false;$getVar[Amis;$replaceText[$replaceText[$checkCondition[$message[1]==$mentioned[1]];true;$mentioned[1]];false;$authorID]]] Ami(s) $replaceText[$replaceText[$checkCondition[$getVar[Amis;$replaceText[$replaceText[$checkCondition[$message[1]==$mentioned[1]];true;$mentioned[1]];false;$authorID]]==0];true;];false;(**$replaceText[$replaceText[$checkCondition[$getVar[Amis;$replaceText[$replaceText[$checkCondition[$message[1]==$mentioned[1]];true;$mentioned[1]];false;$authorID]]==0];true;Aucun];false;$getUserVar[Amis;$authorID]]** sur ce serveur)]
    
    
    ] 
   
    `
    })